# Generated by Django 4.1 on 2022-08-28 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precioDescuento', models.FloatField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reparto', models.TextField()),
                ('director', models.CharField(max_length=100)),
                ('duracion', models.IntegerField()),
                ('genero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoEnCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoCombo', models.IntegerField()),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cineTec_app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagado', models.BooleanField()),
                ('total', models.FloatField()),
                ('combos', models.ManyToManyField(to='cineTec_app.combo')),
                ('productos', models.ManyToManyField(to='cineTec_app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaEntrada', models.TimeField()),
                ('horaSalida', models.TimeField()),
                ('fecha', models.DateField()),
                ('idPelicula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cineTec_app.pelicula')),
                ('idSala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cineTec_app.sala')),
            ],
        ),
        migrations.AddField(
            model_name='combo',
            name='idProductoCombo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cineTec_app.productoencombo'),
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=100)),
                ('fechaCompra', models.DateField()),
                ('idFuncion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cineTec_app.funcion')),
            ],
        ),
        migrations.CreateModel(
            name='AsientoReservado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAsiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cineTec_app.asiento')),
                ('idBoleta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cineTec_app.boleta')),
                ('idFuncion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cineTec_app.funcion')),
            ],
        ),
        migrations.AddField(
            model_name='asiento',
            name='idSala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cineTec_app.sala'),
        ),
    ]
