# Generated by Django 4.1 on 2022-09-14 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cineTec_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedido_Productos',
            new_name='PedidoProductos',
        ),
    ]
