# Generated by Django 4.1 on 2022-09-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineTec_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='combo',
            name='idProductoCombo',
        ),
        migrations.RemoveField(
            model_name='combo',
            name='precioDescuento',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='combo',
            name='Productos',
            field=models.ManyToManyField(to='cineTec_app.producto'),
        ),
        migrations.AddField(
            model_name='combo',
            name='descuento',
            field=models.FloatField(default=20.0),
        ),
        migrations.DeleteModel(
            name='ProductoEnCombo',
        ),
    ]
