# Generated by Django 4.1 on 2022-09-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineTec_app', '0002_rename_pedido_productos_pedidoproductos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='combos',
        ),
        migrations.AlterField(
            model_name='pedidoproductos',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
