# Generated by Django 4.1 on 2022-09-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineTec_app', '0004_pedidocombos_pedido_combos_pedidocombos_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='peliculas'),
        ),
    ]
