# Generated by Django 4.1 on 2022-09-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineTec_app', '0008_alter_pelicula_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='year',
            field=models.CharField(default=2022, max_length=6),
            preserve_default=False,
        ),
    ]
